### ISSUE TITLE
We should need to know, what we want to know!

### ISSUE THREAD

**Issue by enzomero** [khorevigor/edu_cpp_oop#3]
1 ) What we know
2 ) What we need to know
3 ) Split it for few parts
4 ) Split each again...
5 ) Add all of them as a issues into project.
6 ) Discus it, add labels, milestones and etc...
7 ) Start to work!
@khorevigor

**Comment by enzomero** [comment]
Please ask write answers as part of #1 . 
It will be more usefull

**Comment by alooeff** [comment]
Done
