### ISSUE TITLE
1) Lexicographically minimal

### ISSUE THREAD

**Issue by enzomero** [khorevigor/edu_cpp_oop#4]
The task:
In the standard stream, **some words** are given, separated by a space. Each line consists of lowercase Latin letters and has a length of no more than 30 characters. Output to the standard output the lexicographically minimal of them.

Examples
input -> output
milk milkshake month -> milk
c a b -> a
fire fog wood -> fire
@khorevigor

**Comment by alooeff** [comment]
Done

**Comment by alooeff** [comment]
Done. Check it please, at least till 1 billion number.

**Comment by alooeff** [comment]
Already done.

**Comment by enzomero** [comment]
> In the standard stream, some words are given, separated by a space.

I changed conditions. It will be more interesting)

**Comment by alooeff** [comment]
Corrected task done.

**Comment by khorevigor** [comment]
7211364
some comments, keep in mind
