### ISSUE TITLE
2) Greatest common divisor

### ISSUE THREAD

**Issue by enzomero** [khorevigor/edu_cpp_oop#5]
The task:
In stdin two natural numbers are given. Find their greatest common divisor.

Example

stdin -> stdout
25 27 -> 1
12 16 -> 4
13 13 -> 13
@khorevigor

**Comment by alooeff** [comment]
Done. Check it please, at least till 1 billion number.

**Comment by alooeff** [comment]
Check it please, at least till 1 billion number.
Example
stdin -> stdout
1 1 -> 1
1 2 -> 1
1 3 -> 1
...
1 10^9 -> 1
......
2 1 -> 1
2 2 -> 2
2 3 -> 1
...
10^9 10^9 -> 10^9

**Comment by khorevigor** [comment]
7211364
some comments, keep in mind
